name: Update coupons.json (daily)

on:
  schedule:
    - cron: "0 2 * * *"   # run daily at 02:00 UTC
  workflow_dispatch: {}     # allow manual run from Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        working-directory: scraper
        run: npm ci || npm install

      - name: Run scraper
        working-directory: scraper
        run: |
          node index.js --country uae --lang en \
            --slugs shein,adidas,storeus,noon,trendyol,babystore \
            --out ../coupons.json

      - name: Commit & push updated coupons.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet coupons.json; then
            git add coupons.json
            git commit -m "Update coupons.json [skip ci]"
            git push
          else
            echo "No changes in coupons.json"
          fi
